package VMHPOJO;
// Generated Aug 24, 2019 10:14:06 AM by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * Checkexaminationscheduledto generated by hbm2java
 */
public class Checkexaminationscheduledto implements java.io.Serializable {

    private CheckexaminationscheduledtoId id;
    private Date formDate;
    private Date toDate;
    private Date createdDate;
    private Date updatedDate;
    private Boolean isActive;

    public Checkexaminationscheduledto() {
    }

    public Checkexaminationscheduledto(CheckexaminationscheduledtoId id) {
        this.id = id;
    }

    public Checkexaminationscheduledto(CheckexaminationscheduledtoId id, Date formDate, Date toDate) {
        this.id = id;
        this.formDate = formDate;
        this.toDate = toDate;
        this.createdDate = new Date();
        this.updatedDate = new Date();
        this.isActive = true;
    }

    public Checkexaminationscheduledto(CheckexaminationscheduledtoId id, Date formDate, Date toDate, Date createdDate, Date updatedDate, Boolean isActive) {
        this.id = id;
        this.formDate = formDate;
        this.toDate = toDate;
        this.createdDate = createdDate;
        this.updatedDate = updatedDate;
        this.isActive = isActive;
    }

    public CheckexaminationscheduledtoId getId() {
        return this.id;
    }

    public void setId(CheckexaminationscheduledtoId id) {
        this.id = id;
    }

    public Date getFormDate() {
        return this.formDate;
    }

    public void setFormDate(Date formDate) {
        this.formDate = formDate;
    }

    public Date getToDate() {
        return this.toDate;
    }

    public void setToDate(Date toDate) {
        this.toDate = toDate;
    }

    public Date getCreatedDate() {
        return this.createdDate;
    }

    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    public Date getUpdatedDate() {
        return this.updatedDate;
    }

    public void setUpdatedDate(Date updatedDate) {
        this.updatedDate = updatedDate;
    }

    public Boolean getIsActive() {
        return this.isActive;
    }

    public void setIsActive(Boolean isActive) {
        this.isActive = isActive;
    }

}
