package VMHPOJO;
// Generated Aug 24, 2019 10:14:06 AM by Hibernate Tools 4.3.1

/**
 * CheckexaminationscheduledtoId generated by hbm2java
 */
public class CheckexaminationscheduledtoId implements java.io.Serializable {

    private Userdto userName;
    private Classdto classId;
    private Subjectdto subjectId;

    public CheckexaminationscheduledtoId() {
    }

    public CheckexaminationscheduledtoId(Userdto userName, Classdto classId, Subjectdto subjectId) {
        this.userName = userName;
        this.classId = classId;
        this.subjectId = subjectId;
    }

    public Userdto getUserName() {
        return this.userName;
    }

    public void setUserName(Userdto userName) {
        this.userName = userName;
    }

    public Classdto getClassId() {
        return this.classId;
    }

    public void setClassId(Classdto classId) {
        this.classId = classId;
    }

    public Subjectdto getSubjectId() {
        return this.subjectId;
    }

    public void setSubjectId(Subjectdto subjectId) {
        this.subjectId = subjectId;
    }

    public boolean equals(Object other) {
        if ((this == other)) {
            return true;
        }
        if ((other == null)) {
            return false;
        }
        if (!(other instanceof CheckexaminationscheduledtoId)) {
            return false;
        }
        CheckexaminationscheduledtoId castOther = (CheckexaminationscheduledtoId) other;

        return ((this.getUserName() == castOther.getUserName()) || (this.getUserName() != null && castOther.getUserName() != null && this.getUserName().equals(castOther.getUserName())))
                && (this.getClassId() == castOther.getClassId())
                && (this.getSubjectId() == castOther.getSubjectId());
    }

}
