package VMHPOJO;
// Generated Aug 24, 2019 10:14:06 AM by Hibernate Tools 4.3.1

/**
 * CheckexaminationdtoId generated by hbm2java
 */
public class CheckexaminationdtoId implements java.io.Serializable {

    private Studentdto studentId;
    private Userdto userName;
    private Classdto classId;
    private Subjectdto subjectId;

    public CheckexaminationdtoId() {
    }

    public CheckexaminationdtoId(Studentdto studentId, Checkexaminationscheduledto checkExaminationSchedule) {
        this.studentId = studentId;
        this.userName = checkExaminationSchedule.getId().getUserName();
        this.classId = checkExaminationSchedule.getId().getClassId();
        this.subjectId = checkExaminationSchedule.getId().getSubjectId();
    }

    public CheckexaminationdtoId(Studentdto studentId, Userdto userName, Classdto classId, Subjectdto subjectId) {
        this.studentId = studentId;
        this.userName = userName;
        this.classId = classId;
        this.subjectId = subjectId;
    }

    public Studentdto getStudentId() {
        return this.studentId;
    }

    public void setStudentId(Studentdto studentId) {
        this.studentId = studentId;
    }

    public Userdto getUserName() {
        return this.userName;
    }

    public void setUserName(Userdto userName) {
        this.userName = userName;
    }

    public Classdto getClassId() {
        return this.classId;
    }

    public void setClassId(Classdto classId) {
        this.classId = classId;
    }

    public Subjectdto getSubjectId() {
        return this.subjectId;
    }

    public void setSubjectId(Subjectdto subjectId) {
        this.subjectId = subjectId;
    }

    public boolean equals(Object other) {
        if ((this == other)) {
            return true;
        }
        if ((other == null)) {
            return false;
        }
        if (!(other instanceof CheckexaminationdtoId)) {
            return false;
        }
        CheckexaminationdtoId castOther = (CheckexaminationdtoId) other;

        return (this.getStudentId() == castOther.getStudentId())
                && ((this.getUserName() == castOther.getUserName()) || (this.getUserName() != null && castOther.getUserName() != null && this.getUserName().equals(castOther.getUserName())))
                && (this.getClassId() == castOther.getClassId())
                && (this.getSubjectId() == castOther.getSubjectId());
    }

}
