package VMHPOJO;
// Generated Aug 17, 2019 1:37:53 PM by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * Classdto generated by hbm2java
 */
public class Classdto implements java.io.Serializable {

    private int id;
    private String classCode;
    private Date createdDate;
    private Date updatedDate;
    private Boolean isActive;

    public Classdto() {
    }

    public Classdto(String classCode) {
        this.classCode = classCode;
        Date date = new Date();
        this.createdDate = date;
        this.updatedDate = date;
        this.isActive = true;
    }

    public Classdto(String classCode, Date createdDate, Date updatedDate, Boolean isActive) {
        this.classCode = classCode;
        this.createdDate = createdDate;
        this.updatedDate = updatedDate;
        this.isActive = isActive;
    }

    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getClassCode() {
        return this.classCode;
    }

    public void setClassCode(String classCode) {
        this.classCode = classCode;
    }

    public Date getCreatedDate() {
        return this.createdDate;
    }

    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    public Date getUpdatedDate() {
        return this.updatedDate;
    }

    public void setUpdatedDate(Date updatedDate) {
        this.updatedDate = updatedDate;
    }

    public Boolean getIsActive() {
        return this.isActive;
    }

    public void setIsActive(Boolean isActive) {
        this.isActive = isActive;
    }
    
    // The "toString" method will be used by the JComboBox to generate the label for the item
    @Override
    public String toString() {
        return getClassCode();
    }
}
