package VMHPOJO;
// Generated Aug 17, 2019 4:28:30 PM by Hibernate Tools 4.3.1

/**
 * ScheduledtoId generated by hbm2java
 */
public class ScheduledtoId implements java.io.Serializable {

    private Classdto classId;
    private Subjectdto subjectId;

    public ScheduledtoId() {
    }

    public ScheduledtoId(Classdto classId, Subjectdto subjectId) {
        this.classId = classId;
        this.subjectId = subjectId;
    }

    public Classdto getClassId() {
        return this.classId;
    }

    public void setClassId(Classdto classId) {
        this.classId = classId;
    }

    public Subjectdto getSubjectId() {
        return this.subjectId;
    }

    public void setSubjectId(Subjectdto subjectId) {
        this.subjectId = subjectId;
    }

    public boolean equals(Object other) {
        if ((this == other)) {
            return true;
        }
        if ((other == null)) {
            return false;
        }
        if (!(other instanceof ScheduledtoId)) {
            return false;
        }
        ScheduledtoId castOther = (ScheduledtoId) other;

        return (this.getClassId() == castOther.getClassId())
                && (this.getSubjectId() == castOther.getSubjectId());
    }
}
