package VMHPOJO;
// Generated Aug 17, 2019 4:28:30 PM by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * Scheduledto generated by hbm2java
 */
public class Scheduledto implements java.io.Serializable {

    private ScheduledtoId id;
    private String classRoom;
    private Date createdDate;
    private Date updatedDate;
    private Boolean isActive;

    public Scheduledto() {
    }

    public Scheduledto(ScheduledtoId id, String classRoom) {
        this.id = id;
        this.classRoom = classRoom;
        this.createdDate = new Date();
        this.updatedDate = new Date();
        this.isActive = true;        
    }

    public Scheduledto(ScheduledtoId id, String classRoom, Date createdDate, Date updatedDate, Boolean isActive) {
        this.id = id;
        this.classRoom = classRoom;
        this.createdDate = createdDate;
        this.updatedDate = updatedDate;
        this.isActive = isActive;
    }

    public ScheduledtoId getId() {
        return this.id;
    }

    public void setId(ScheduledtoId id) {
        this.id = id;
    }

    public String getClassRoom() {
        return this.classRoom;
    }

    public void setClassRoom(String classRoom) {
        this.classRoom = classRoom;
    }

    public Date getCreatedDate() {
        return this.createdDate;
    }

    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    public Date getUpdatedDate() {
        return this.updatedDate;
    }

    public void setUpdatedDate(Date updatedDate) {
        this.updatedDate = updatedDate;
    }

    public Boolean getIsActive() {
        return this.isActive;
    }

    public void setIsActive(Boolean isActive) {
        this.isActive = isActive;
    }

}
