package VMHPOJO;
// Generated Aug 17, 2019 4:28:30 PM by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * Studentdto generated by hbm2java
 */
public class Studentdto implements java.io.Serializable {

    private int id;
    private String studentCode;
    private String studentName;
    private Integer gender;
    private String identityNumber;
    private int classId;
    private Date createdDate;
    private Date updatedDate;
    private Boolean isActive;

    public Studentdto() {
    }

    public Studentdto(String studentCode, String studentName, Integer gender, String identityNumber, int classId) {
        this.studentCode = studentCode;
        this.studentName = studentName;
        this.gender = gender;
        this.identityNumber = identityNumber;
        this.classId = classId;
        this.createdDate = new Date();
        this.updatedDate = new Date();
        this.isActive = true;
    }

    public Studentdto(int id, String studentCode, String studentName, Integer gender, String identityNumber, int classId, Date createdDate, Date updatedDate, Boolean isActive) {
        this.id = id;
        this.studentCode = studentCode;
        this.studentName = studentName;
        this.gender = gender;
        this.identityNumber = identityNumber;
        this.classId = classId;
        this.createdDate = createdDate;
        this.updatedDate = updatedDate;
        this.isActive = isActive;
    }

    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getStudentCode() {
        return this.studentCode;
    }

    public void setStudentCode(String studentCode) {
        this.studentCode = studentCode;
    }

    public String getStudentName() {
        return this.studentName;
    }

    public void setStudentName(String studentName) {
        this.studentName = studentName;
    }

    public Integer getGender() {
        return this.gender;
    }

    public void setGender(Integer gender) {
        this.gender = gender;
    }

    public String getIdentityNumber() {
        return this.identityNumber;
    }

    public void setIdentityNumber(String identityNumber) {
        this.identityNumber = identityNumber;
    }

    public int getClassId() {
        return this.classId;
    }

    public void setClassId(int classId) {
        this.classId = classId;
    }

    public Date getCreatedDate() {
        return this.createdDate;
    }

    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    public Date getUpdatedDate() {
        return this.updatedDate;
    }

    public void setUpdatedDate(Date updatedDate) {
        this.updatedDate = updatedDate;
    }

    public Boolean getIsActive() {
        return this.isActive;
    }

    public void setIsActive(Boolean isActive) {
        this.isActive = isActive;
    }
    // The "toString" method will be used by the JComboBox to generate the label for the item

    @Override
    public String toString() {
        return getStudentName();
    }
}
