package VMHPOJO;
// Generated Aug 17, 2019 4:28:30 PM by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * Transcriptdto generated by hbm2java
 */
public class Transcriptdto implements java.io.Serializable {

    private TranscriptdtoId id;
    private float scoresMid;
    private float scoresEnd;
    private float scoresOther;
    private float scoresSum;
    private Date createdDate;
    private Date updatedDate;
    private Boolean isActive;

    public Transcriptdto() {
    }

    public Transcriptdto(TranscriptdtoId id) {
        this.id = id;
        this.scoresMid = 0;
        this.scoresEnd = 0;
        this.scoresOther = 0;
        this.scoresSum = 0;
        this.createdDate = new Date();
        this.updatedDate = new Date();
        this.isActive = true;
    }

    public Transcriptdto(TranscriptdtoId id, float scoresMid, float scoresEnd, float scoresOther, float scoresSum) {
        this.id = id;
        this.scoresMid = scoresMid;
        this.scoresEnd = scoresEnd;
        this.scoresOther = scoresOther;
        this.scoresSum = scoresSum;
        this.createdDate = new Date();
        this.updatedDate = new Date();
        this.isActive = true;
    }

    public Transcriptdto(TranscriptdtoId id, float scoresMid, float scoresEnd, float scoresOther, float scoresSum, Date createdDate, Date updatedDate, Boolean isActive) {
        this.id = id;
        this.scoresMid = scoresMid;
        this.scoresEnd = scoresEnd;
        this.scoresOther = scoresOther;
        this.scoresSum = scoresSum;
        this.createdDate = createdDate;
        this.updatedDate = updatedDate;
        this.isActive = isActive;
    }

    public TranscriptdtoId getId() {
        return this.id;
    }

    public void setId(TranscriptdtoId id) {
        this.id = id;
    }

    public float getScoresMid() {
        return this.scoresMid;
    }

    public void setScoresMid(float scoresMid) {
        this.scoresMid = scoresMid;
    }

    public float getScoresEnd() {
        return this.scoresEnd;
    }

    public void setScoresEnd(float scoresEnd) {
        this.scoresEnd = scoresEnd;
    }

    public float getScoresOther() {
        return this.scoresOther;
    }

    public void setScoresOther(float scoresOther) {
        this.scoresOther = scoresOther;
    }

    public float getScoresSum() {
        return this.scoresSum;
    }

    public void setScoresSum(float scoresSum) {
        this.scoresSum = scoresSum;
    }

    public Date getCreatedDate() {
        return this.createdDate;
    }

    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    public Date getUpdatedDate() {
        return this.updatedDate;
    }

    public void setUpdatedDate(Date updatedDate) {
        this.updatedDate = updatedDate;
    }

    public Boolean getIsActive() {
        return this.isActive;
    }

    public void setIsActive(Boolean isActive) {
        this.isActive = isActive;
    }

}
