package VMHPOJO;
// Generated Aug 17, 2019 4:28:30 PM by Hibernate Tools 4.3.1

/**
 * TranscriptdtoId generated by hbm2java
 */
public class TranscriptdtoId implements java.io.Serializable {

    private Studentdto studentId;
    private Classdto classId;
    private Subjectdto subjectId;

    public TranscriptdtoId() {
    }

    public TranscriptdtoId(Studentdto studentId, ScheduledtoId  subjectdtoId) {
        this.studentId = studentId;
        this.classId = subjectdtoId.getClassId();
        this.subjectId = subjectdtoId.getSubjectId();
    }

    public TranscriptdtoId(Studentdto studentId, Classdto classId, Subjectdto subjectId) {
        this.studentId = studentId;
        this.classId = classId;
        this.subjectId = subjectId;
    }

    public Studentdto getStudentId() {
        return this.studentId;
    }

    public void setStudentId(Studentdto studentId) {
        this.studentId = studentId;
    }

    public Classdto getClassId() {
        return this.classId;
    }

    public void setClassId(Classdto classId) {
        this.classId = classId;
    }

    public Subjectdto getSubjectId() {
        return this.subjectId;
    }

    public void setSubjectId(Subjectdto subjectId) {
        this.subjectId = subjectId;
    }

    public boolean equals(Object other) {
        if ((this == other)) {
            return true;
        }
        if ((other == null)) {
            return false;
        }
        if (!(other instanceof TranscriptdtoId)) {
            return false;
        }
        TranscriptdtoId castOther = (TranscriptdtoId) other;

        return (this.getStudentId() == castOther.getStudentId())
                && (this.getClassId() == castOther.getClassId())
                && (this.getSubjectId() == castOther.getSubjectId());
    }
}
