package VMHPOJO;
// Generated Aug 17, 2019 1:37:53 PM by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * Userdto generated by hbm2java
 */
public class Userdto implements java.io.Serializable {

    private String userName;
    private String password;
    private Boolean isAdmin;
    private Date createdDate;
    private Date updatedDate;
    private Boolean isActive;

    public Userdto() {
    }

    public Userdto(String userName, String password, Boolean isAdmin) {
        this.userName = userName;
        this.password = password;
        this.isAdmin = isAdmin;
        Date date = new Date();
        this.createdDate = date;
        this.updatedDate = date;
        this.isActive = true;
    }

    public Userdto(String userName, String password, Boolean isAdmin, Date createdDate, Date updatedDate, Boolean isActive) {
        this.userName = userName;
        this.password = password;
        this.isAdmin = isAdmin;
        this.createdDate = createdDate;
        this.updatedDate = updatedDate;
        this.isActive = isActive;
    }

    public String getUserName() {
        return this.userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    public String getPassword() {
        return this.password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public Boolean getIsAdmin() {
        return this.isAdmin;
    }

    public void setIsAdmin(Boolean isAdmin) {
        this.isAdmin = isAdmin;
    }

    public Date getCreatedDate() {
        return this.createdDate;
    }

    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    public Date getUpdatedDate() {
        return this.updatedDate;
    }

    public void setUpdatedDate(Date updatedDate) {
        this.updatedDate = updatedDate;
    }

    public Boolean getIsActive() {
        return this.isActive;
    }

    public void setIsActive(Boolean isActive) {
        this.isActive = isActive;
    }

}
